name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: tag
        run: |
          docker pull hello-world:latest
          docker tag hello-world:latest docker.io/liquibase/liquibase:4.32.0
        
      - name: Run Hello World
        run: |
          docker run liquibase/liquibase:4.32.0

      - uses: actions/checkout@v4
      
      - name: run docker build
        run: |
          pwd
          ls -lrt
          docker build ./Dockerfile
