name: Test2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: liquibaseを実行
        run: |
          docker run --rm -v ${{ github.workspace }}:/github/workspace -w /github/workspace uzresk/liquibase/liquibase:4.32.0 update
